# Generated by Django 2.1.5 on 2019-01-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='out_of_stock',
            field=models.BooleanField(default=False),
        ),
    ]
