# Generated by Django 2.1.5 on 2019-01-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_challenge', '0002_item_out_of_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('CPU', 'Processor'), ('RAM', 'Memory'), ('GPU', 'Video Card')], max_length=40, null=True),
        ),
    ]
