# Generated by Django 2.1.5 on 2019-01-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_challenge', '0004_shoppingcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='items',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
