# Generated by Django 2.1.5 on 2019-01-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_challenge', '0005_auto_20190116_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='items',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
