# Generated by Django 2.1.5 on 2019-01-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_challenge', '0006_auto_20190116_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
